# This is an example with only required properties:
version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/app"
    update_schedule: "daily"
    default_reviewers:
      - "pokk"
